import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-gray-100`}>
                {/* Header Section */}
                <header className="bg-white shadow-lg p-6 text-center">
                    <h1 className="text-3xl font-bold"> Mastering the Nextjs for Moderan web development</h1>
                    <p className="text-gray-500">From zero to hero with Next.js—your journey to full-stack expertise starts here</p>
                </header>

                {/* Main Navigation */}
                <nav className="bg-gray-200 p-4">
                    <ul className="flex justify-center space-x-6">
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href="/about">About</Link>
                        </li>
                        <li>
                            <Link href="/Blogs">Blogs</Link>
                        </li>
                        <li>
                            <Link href="/posts">Post</Link>
                        </li>
                        
                    </ul>
                </nav>

                {/* Main Content Layout */}
                <div className="container mx-auto p-6 grid grid-cols-12 gap-6">
                    {/* Sidebar */}
                    <aside className="col-span-3 bg-white p-4 shadow-md">
                        <h2 className="text-xl font-bold mb-4">Side bar link</h2>
                        <ul className="space-y-2">
                            {[...Array(7)].map((_, index) => (
                                <li key={index} className="border-b border-gray-300 py-2">
                                    <Link href={`/menu${index + 1}`}>
                                        Link 1 {index + 1}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                        
                        <h2 className="text-xl font-bold mt-6 mb-4">Block</h2>
                        <p className="text-gray-600">Enter block content here...</p>
                    </aside>

                    {/* Main Content */}
                    <main className="col-span-9 bg-white p-6 shadow-md">
                        {children}
                    </main>
                </div>

                {/* Footer */}
                <footer className="bg-gray-200 text-center py-4 mt-6">
                    <p>&copy; 2014</p>
                </footer>
                <footer className="bg-gray-200 text-center py-4 mt-6">
                    <p>&copy; 2014</p>
                </footer>
            </body>
        </html>
    );
}
